server:
  port: 8082

spring:
  application:
    name: credit-assessment-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=creditdb;encrypt=false
    username: sa
    password: LoanApp@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-assessment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/